spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lifer}
    username: ${DATABASE_USERNAME:lifer}
    password: ${DATABASE_PASSWORD:lifer}
  flyway:
    sql-migration-prefix: "DATE_"

setting:
  telegram:
    bot:
      token: ${TELEGRAM_BOT_TOKEN}
      username: ${TELEGRAM_BOT_USERNAME}

