version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "lifer"
      POSTGRES_USER: "lifer"
      POSTGRES_PASSWORD: "lifer"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"